imports:
    - "cloudify.types"

blueprint:
    name: "single_node"
    nodes:
        -   name: "single_node"
            type: "mock_type"

types:
    mock_type:
        derived_from: cloudify.types.base
        workflows:
            create:
                radial: |
                    define sleep_workflow_workflow
                        sleep '100s'
